// Generated by CoffeeScript 2.5.1
import {
  r4r,
  br,
  div,
  indented
} from '../js/utils.js';

r4r(() => {
  return div({
    style: "font-size:20px"
  }, div({
    style: "font-size:30px"
  }, `Kontakt`), indented(` 
Seniorer:
	Tom Wedberg, ordf
		Telefon
			070-797 24 13
		Mail
			sparbax (at) hotmail.com
	Plats
		Time Hotel, Vanadisvägen 12
	Torsdagar
		18:30-
	Avgift
		1200:- per år
 
Juniorer:
	David Douhan
		Telefon
			072-362 70 50
		Mail
			douhan.music (at) gmail.com
	Plats
		Norra Real, Roslagsgatan 1
	Torsdagar
		17:00-19:00
	Tisdagar
		17:00-19:00
	Avgift
		1200:- per termin
 
Plusgiro
	40 07 99-3
Organisationsnummer
	80 20 09 - 3038`));
});

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoia29udGFrdC5qcyIsInNvdXJjZVJvb3QiOiIuLiIsInNvdXJjZXMiOlsiY29mZmVlXFxrb250YWt0LmNvZmZlZSJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiO0FBQUEsT0FBQTtFQUFRLEdBQVI7RUFBWSxFQUFaO0VBQWUsR0FBZjtFQUFtQixRQUFuQjtDQUFBLE1BQUE7O0FBRUEsR0FBQSxDQUFJLENBQUEsQ0FBQSxHQUFBO1NBQ0gsR0FBQSxDQUFJO0lBQUMsS0FBQSxFQUFNO0VBQVAsQ0FBSixFQUNDLEdBQUEsQ0FBSTtJQUFDLEtBQUEsRUFBTTtFQUFQLENBQUosRUFBOEIsQ0FBQSxPQUFBLENBQTlCLENBREQsRUFHQyxRQUFBLENBQVMsQ0FBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Z0JBQUEsQ0FBVCxDQUhEO0FBREcsQ0FBSiIsInNvdXJjZXNDb250ZW50IjpbImltcG9ydCB7cjRyLGJyLGRpdixpbmRlbnRlZH0gZnJvbSAnLi4vanMvdXRpbHMuanMnXHJcblxyXG5yNHIgPT5cclxuXHRkaXYge3N0eWxlOlwiZm9udC1zaXplOjIwcHhcIn0sXHJcblx0XHRkaXYge3N0eWxlOlwiZm9udC1zaXplOjMwcHhcIn0sIFwiXCJcIlxyXG5cdFx0XHRLb250YWt0XCJcIlwiXHJcblx0XHRpbmRlbnRlZCBcIlwiXCJcclxuXHRcdCBcclxuXHRcdFNlbmlvcmVyOlxyXG5cdFx0XHRUb20gV2VkYmVyZywgb3JkZlxyXG5cdFx0XHRcdFRlbGVmb25cclxuXHRcdFx0XHRcdDA3MC03OTcgMjQgMTNcclxuXHRcdFx0XHRNYWlsXHJcblx0XHRcdFx0XHRzcGFyYmF4IChhdCkgaG90bWFpbC5jb21cclxuXHRcdFx0UGxhdHNcclxuXHRcdFx0XHRUaW1lIEhvdGVsLCBWYW5hZGlzdsOkZ2VuIDEyXHJcblx0XHRcdFRvcnNkYWdhclxyXG5cdFx0XHRcdDE4OjMwLVxyXG5cdFx0XHRBdmdpZnRcclxuXHRcdFx0XHQxMjAwOi0gcGVyIMOlclxyXG5cdFx0IFxyXG5cdFx0SnVuaW9yZXI6XHJcblx0XHRcdERhdmlkIERvdWhhblxyXG5cdFx0XHRcdFRlbGVmb25cclxuXHRcdFx0XHRcdDA3Mi0zNjIgNzAgNTBcclxuXHRcdFx0XHRNYWlsXHJcblx0XHRcdFx0XHRkb3VoYW4ubXVzaWMgKGF0KSBnbWFpbC5jb21cclxuXHRcdFx0UGxhdHNcclxuXHRcdFx0XHROb3JyYSBSZWFsLCBSb3NsYWdzZ2F0YW4gMVxyXG5cdFx0XHRUb3JzZGFnYXJcclxuXHRcdFx0XHQxNzowMC0xOTowMFxyXG5cdFx0XHRUaXNkYWdhclxyXG5cdFx0XHRcdDE3OjAwLTE5OjAwXHJcblx0XHRcdEF2Z2lmdFxyXG5cdFx0XHRcdDEyMDA6LSBwZXIgdGVybWluXHJcblx0XHQgXHJcblx0XHRQbHVzZ2lyb1xyXG5cdFx0XHQ0MCAwNyA5OS0zXHJcblx0XHRPcmdhbmlzYXRpb25zbnVtbWVyXHJcblx0XHRcdDgwIDIwIDA5IC0gMzAzOFxyXG5cdFx0XCJcIlwiXHJcbiJdfQ==
//# sourceURL=c:\github\2023-023-Wasa-Search\coffee\kontakt.coffee