// Generated by CoffeeScript 2.5.1
var URL, btn, keypress;

import {
  r4r,
  div,
  button,
  input,
  br
} from '../js/utils.js';

URL = "https://www.wasask.se/aaawasa/wordpress/?s=";

btn = null;

keypress = (e) => {
  if (e.keyCode === 13) {
    return btn.click();
  }
};

r4r(() => {
  var data;
  return div({
    style: "width:600px"
  }, "Sök inom Wasa Schackklubbs hemsida:", data = input({
    style: "width:600px; font-size:32px;",
    onkeypress: keypress
  }), br({}), btn = button({
    type: "submit",
    style: "width:608px; font-size:32px;",
    onclick: () => {
      return window.location = URL + data.value;
    }
  }, "Sök"));
});

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoic2tldGNoLmpzIiwic291cmNlUm9vdCI6Ii4uIiwic291cmNlcyI6WyJjb2ZmZWVcXHNrZXRjaC5jb2ZmZWUiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IjtBQUFBLElBQUEsR0FBQSxFQUFBLEdBQUEsRUFBQTs7QUFBQSxPQUFBO0VBQVEsR0FBUjtFQUFZLEdBQVo7RUFBZ0IsTUFBaEI7RUFBdUIsS0FBdkI7RUFBNkIsRUFBN0I7Q0FBQSxNQUFBOztBQUVBLEdBQUEsR0FBTTs7QUFDTixHQUFBLEdBQU07O0FBRU4sUUFBQSxHQUFXLENBQUMsQ0FBRCxDQUFBLEdBQUE7RUFBTyxJQUFHLENBQUMsQ0FBQyxPQUFGLEtBQWEsRUFBaEI7V0FBd0IsR0FBRyxDQUFDLEtBQUosQ0FBQSxFQUF4Qjs7QUFBUDs7QUFFWCxHQUFBLENBQUksQ0FBQSxDQUFBLEdBQUE7QUFDSixNQUFBO1NBQUMsR0FBQSxDQUFJO0lBQUMsS0FBQSxFQUFNO0VBQVAsQ0FBSixFQUNDLHFDQURELEVBRUMsSUFBQSxHQUFPLEtBQUEsQ0FBTTtJQUFDLEtBQUEsRUFBTSw4QkFBUDtJQUF1QyxVQUFBLEVBQWE7RUFBcEQsQ0FBTixDQUZSLEVBR0MsRUFBQSxDQUFHLENBQUEsQ0FBSCxDQUhELEVBSUMsR0FBQSxHQUFNLE1BQUEsQ0FBTztJQUFDLElBQUEsRUFBSyxRQUFOO0lBQWdCLEtBQUEsRUFBTSw4QkFBdEI7SUFBcUQsT0FBQSxFQUFTLENBQUEsQ0FBQSxHQUFBO2FBQUcsTUFBTSxDQUFDLFFBQVAsR0FBa0IsR0FBQSxHQUFNLElBQUksQ0FBQztJQUFoQztFQUE5RCxDQUFQLEVBQTRHLEtBQTVHLENBSlA7QUFERyxDQUFKIiwic291cmNlc0NvbnRlbnQiOlsiaW1wb3J0IHtyNHIsZGl2LGJ1dHRvbixpbnB1dCxicn0gZnJvbSAnLi4vanMvdXRpbHMuanMnXHJcblxyXG5VUkwgPSBcImh0dHBzOi8vd3d3Lndhc2Fzay5zZS9hYWF3YXNhL3dvcmRwcmVzcy8/cz1cIlxyXG5idG4gPSBudWxsXHJcblxyXG5rZXlwcmVzcyA9IChlKSA9PiBpZiBlLmtleUNvZGUgPT0gMTMgdGhlbiBidG4uY2xpY2soKVxyXG5cclxucjRyID0+XHJcblx0ZGl2IHtzdHlsZTpcIndpZHRoOjYwMHB4XCJ9LFxyXG5cdFx0XCJTw7ZrIGlub20gV2FzYSBTY2hhY2trbHViYnMgaGVtc2lkYTpcIixcclxuXHRcdGRhdGEgPSBpbnB1dCB7c3R5bGU6XCJ3aWR0aDo2MDBweDsgZm9udC1zaXplOjMycHg7XCIsIG9ua2V5cHJlc3MgOiBrZXlwcmVzc31cclxuXHRcdGJyIHt9XHJcblx0XHRidG4gPSBidXR0b24ge3R5cGU6XCJzdWJtaXRcIiwgc3R5bGU6XCJ3aWR0aDo2MDhweDsgZm9udC1zaXplOjMycHg7XCIsb25jbGljazogPT4gd2luZG93LmxvY2F0aW9uID0gVVJMICsgZGF0YS52YWx1ZX0sXCJTw7ZrXCJcclxuIl19
//# sourceURL=c:\github\2023-023-Wasa-Search\coffee\sketch.coffee