import os
import time

TOUR  = "https://member.schack.se/ShowTournamentServlet?id="
ANMÄL = "https://member.schack.se/turnering/"
BB2   = "https://storage.googleapis.com/bildbanken2/index.html?query="
WASA  = "https://www.wasask.se/"
SMALL = "https://storage.googleapis.com/bildbanken2/small/"

count = 0

def countTabs (s) :
	n = 0
	for c in s:
		if c != "\t": break
		n += 1
	return n

def a(arr, prefix="", suffix=""):
	if len(arr) == 3: # COMMAND | text | link
		text = arr[1]
		link = arr[2]
		return "<a href='{link}'>{text}</a>".format(text=text, link=prefix + link + suffix)
	elif len(arr) == 4: # COMMAND | prompt | text | link
		prompt = arr[1]
		text = arr[2]
		link = arr[3]
		return "{prompt}<a href='{link}'>{text}</a>".format(prompt=prompt, text=text, link=prefix + link + suffix)
	else:
		print('Error message')

def link(arr): return a(arr)
def tour(arr): return a(arr, TOUR)
def anmäl(arr): return a(arr, ANMÄL, '/anmalan')
def bb2(arr): return a(arr, BB2)
def wasa(arr): return a(arr, WASA)
def bold(arr): return "<b>"+arr[1]+"</b>"
def br(): return "<br>"
def h2(arr): return "<h2>"+arr[1]+"</h2>"
def small(arr): return a(arr, SMALL)

def transpile (filename) :
	global count
	with open('lean/'+filename,encoding='utf8') as f:
		s = f.read()
	res = []
	res.append('<!-- Generated by lean2html 1.0 -->')
	res.append('<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />')
	res.append('<head><title>' + filename.replace('.lean','') + '</title>')
	res.append('<style>')
	res.append('\t.I0 {margin-left: 0px}')
	res.append('\t.I1 {margin-left: 20px}')
	res.append('\t.I2 {margin-left: 40px}')
	res.append('\t.I3 {margin-left: 60px}')
	res.append('\t.I4 {margin-left: 80px}')
	res.append('</style>')
	res.append('</head>')
	res.append('<body>')

	res.append('<div style="font-family:monospace; font-size:16px">')
	for line in s.split("\n"):
		count += 1
		n = countTabs(line)
		line = line.replace('<red>','<font color=red>').replace('</red>','</font>')
		line = line.replace('<green>','<font color=green>').replace('</green>','</font>')
		line = line.strip()
		arr = line.split("|")
		cmd = arr[0]

		if cmd == "LINK" :    line = link(arr)
		elif cmd == "TOUR" :  line = tour(arr)
		elif cmd == "ANMÄL" : line = anmäl(arr)
		elif cmd == "BB2" :   line = bb2(arr)
		elif cmd == "WASA" :  line = wasa(arr)
		elif cmd == "A" :     line = link(arr)
		elif cmd == "SMALL" : line = small(arr)
		elif cmd == "" :      line = br()
		elif cmd == "HEADER" : line = h2(arr)
		elif cmd == "BOLD" :  line = bold(arr)
		elif cmd == "DOT" :   line = " • "

		if cmd == "" or cmd == 'A' or cmd == 'DOT':
			res.append(("\t"*n) + line)
		else:
			res.append(("\t"*n) + '<div class="I'+str(n)+'">' + line + '</div>')
	res.append('</div>')
	res.append('</body>')
	with open(filename.replace('.lean','.html'), 'w', encoding='utf8') as g:
		g.write('\n'.join(res))

start = time.time()
for filename in os.listdir('lean'):
	transpile(filename)
print(round(count/(time.time()-start)),'lines/sec')