import os
import time

count = 0

def countTabs (s) :
	n = 0
	for c in s:
		if c != "\t": break
		n += 1
	return n

TOUR  = "https://member.schack.se/ShowTournamentServlet?id="
ANMÄL = "https://member.schack.se/turnering/"
BB2   = "https://storage.googleapis.com/bildbanken2/index.html?query="
WASA  = "https://www.wasask.se/"

def a(text,link): return "<a href='{link}'>{text}</a>".format(link=link,text=text)
def link(arr): return a(arr[1], arr[2])
def tour(arr): return a(arr[1], TOUR+arr[2])
def anmäl(arr): return a(arr[1], ANMÄL+arr[2]+'/anmalan')
def bb2(arr): return a(arr[1], BB2+arr[2])
def wasa(arr): return a(arr[1], WASA+arr[2])
def bold(text): return "<b>"+text+"</b>"
def br(): return "<br>"
def h2(text): return "<h2>"+text+"</h2>"

def transpile (filename) :
	global count
	with open('xyz/'+filename,encoding='utf8') as f:
		s = f.read()
	res = []
	res.append('<!-- Generated by xyz2html 1.0 -->')
	res.append('<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />')
	res.append('<head><title>' + filename.replace('.xyz','') + '</title>')
	res.append('<style>')
	res.append('  .I0 {margin-left: 0px}')
	res.append('  .I1 {margin-left: 20px}')
	res.append('  .I2 {margin-left: 40px}')
	res.append('  .I3 {margin-left: 60px}')
	res.append('  .I4 {margin-left: 80px}')
	res.append('</style>')
	res.append('</head>')
	res.append('<body>')

	res.append('<div style="font-family:monospace; font-size:16px">')
	for line in s.split("\n"):
		count += 1
		n = countTabs(line)
		line = line.replace('<red>','<font color=red>').replace('</red>','</font>')
		line = line.replace('<green>','<font color=green>').replace('</green>','</font>')
		line = line.strip()
		arr = line.split("|")
		cmd = arr[0]

		if cmd == "LINK" :    line = link(arr)
		elif cmd == "TOUR" :  line = tour(arr)
		elif cmd == "ANMÄL" : line = anmäl(arr) #{href:ANMÄL + arr[2] + "/anmalan"}, arr[1]
		elif cmd == "" :      line = br()
		elif cmd == "HEADER" : line = h2(arr[1]) # {}, arr[1]
		elif cmd == "BB2" :   line = bb2(arr) #{href:BB2 + arr[2]},arr[1]
		elif cmd == "WASA" :  line = wasa(arr) # {href:WASA + arr[2]},arr[1]
		elif cmd == "BOLD" :  line = bold(arr[1])
		elif cmd == "DOT" :   line = " • "
		elif cmd == "A" :     line = link(arr)

		if cmd == "" or cmd == 'A' or cmd == 'DOT':
			res.append(("  "*n) + line)
		else:
			res.append(("  "*n) + '<div class="I'+str(n)+'">' + line + '</div>')
	res.append('</div>')
	res.append('</body>')
	with open(filename.replace('.xyz','.html'), 'w', encoding='utf8') as g:
		g.write('\n'.join(res))

start = time.time()
for filename in os.listdir('xyz'):
	transpile(filename)
print(round(count/(time.time()-start)),'lines/sec')