import {r4r,a,div,h2,p} from '../js/utils.js'

r4r => div {style:"font-family:monospace; font-size:16px"},
	h2 {},"Wasa Schackklubb"
	a {href:"https://storage.googleapis.com/bildbanken2/index.html?query=Wasa"}, "Bilder"
	" • "
	a {href:"inbjudningar.html"}, "Inbjudningar"
	" • "
	a {href:"junior.html"}, "Junior"
	" • "
	a {href:"http://wasask.se/aaawasa/wordpress"}, "Nyheter"
	" • "
	a {href:"https://resultat.schack.se/ShowClubRatingServlet?clubid=38481"}, "Ranking"
	" • "
	a {href:"senior.html"}, "Senior"
	" • "
	a {href:"speldatum.html"}, "Speldatum"
	" • "
	a {href:"styrelse.html"}, "Styrelse"
	" • "
	a {href:"search.html"}, "Sök"
	p {}, "Denna sida är minimal för att även fungera på mobiler."
